### ISSUE TITLE
[TS-614] Invalid Request

### ISSUE THREAD

**Issue by abmmhasan** [codacy/codacy-analysis-cli-action#120]
```
Run github/codeql-action/upload-sarif@main
Uploading results
  Processing sarif files: ["results.sarif"]
  Uploading results
  Error: Invalid request.
  
  1 item required; only 0 were supplied.
  RequestError [HttpError]: Invalid request.
  
  1 item required; only 0 were supplied.
      at /home/runner/work/_actions/github/codeql-action/main/node_modules/@octokit/request/dist-node/index.js:86:21
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async requestWithGraphqlErrorHandling (/home/runner/work/_actions/github/codeql-action/main/node_modules/@octokit/plugin-retry/dist-node/index.js:71:20)
      at async Job.doExecute (/home/runner/work/_actions/github/codeql-action/main/node_modules/bottleneck/light.js:405:[18](https://github.com/abmmhasan/InterMix/actions/runs/6492062746/job/17630344481?pr=19#step:4:19)) {
    status: 422,
    response: {
      url: 'https://api.github.com/repos/abmmhasan/InterMix/code-scanning/analysis',
      status: 422,
      headers: {
        'access-control-allow-origin': '*',
        'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
        connection: 'close',
        'content-length': '123',
        'content-security-policy': "default-src 'none'",
        'content-type': 'application/json; charset=utf-8',
        date: 'Thu, 12 Oct 2023 06:25:38 GMT',
        'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
        server: 'GitHub.com',
        'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
        vary: 'Accept-Encoding, Accept, X-Requested-With',
        'x-content-type-options': 'nosniff',
        'x-frame-options': 'deny',
        'x-github-api-version-selected': '2022-11-28',
        'x-github-media-type': 'github.v3; format=json',
        'x-github-request-id': '7C03:8A7C:1C4AD3E:39889D0:65279161',
        'x-ratelimit-limit': '1000',
        'x-ratelimit-remaining': '998',
        'x-ratelimit-reset': '1697093466',
        'x-ratelimit-resource': 'code_scanning_upload',
        'x-ratelimit-used': '2',
        'x-xss-protection': '0'
      },
      data: {
        message: 'Invalid request.\n\n1 item required; only 0 were supplied.',
        documentation_url: 'https://docs.github.com/rest'
      }
    },
    request: {
      method: 'PUT',
      url: 'https://api.github.com/repos/abmmhasan/InterMix/code-scanning/analysis',
      headers: {
        accept: 'application/vnd.github.v3+json',
        'user-agent': 'CodeQL-Action/2.22.2 octokit-core.js/3.6.0 Node.js/16.20.1 (linux; x64)',
        authorization: 'token [REDACTED]',
        'content-type': 'application/json; charset=utf-8'
      },
      body: '{"commit_oid":"63ff8c93ebdfb0bbb1d7704eca9b1ef3c1d54afe","ref":"refs/pull/[19](https://github.com/abmmhasan/InterMix/actions/runs/6492062746/job/17630344481?pr=19#step:4:20)/merge","analysis_key":".github/workflows/codacy.yml:codacy-security-scan","analysis_name":"Codacy Security Scan","sarif":"H4sIAAAAAAAAA6tWKkstKs7Mz1OyUjLSM9QzUNJRKirNK1ayio6tBQBSlZKzHQAAAA==","workflow_run_id":649[20](https://github.com/abmmhasan/InterMix/actions/runs/6492062746/job/17630344481?pr=19#step:4:21)62746,"workflow_run_attempt":1,"checkout_uri":"file:///home/runner/work/InterMix/InterMix","environment":"null","started_at":"2023-10-12T06:25:36.907Z","tool_names":[],"base_ref":"refs/heads/main","base_sha":"e2d582d4c145c7e7783b01c62646901c806[21](https://github.com/abmmhasan/InterMix/actions/runs/6492062746/job/17630344481?pr=19#step:4:22)[27](https://github.com/abmmhasan/InterMix/actions/runs/6492062746/job/17630344481?pr=19#step:4:28)d"}',
      request: { agent: [Agent], hook: [Function: bound bound register] }
    }
  }
```

**Comment by abmmhasan** [comment]
any update on this?
