### ISSUE TITLE
[CY-6112] Markdownlint error right after pulling docker image in github-cli-action

### ISSUE THREAD

**Issue by mrtnbm** [codacy/codacy-analysis-cli-action#79]
Hello, I'm using the following configuration in my github workflow:
```yaml
- name: Run Codacy Analysis CLI
      uses: codacy/codacy-analysis-cli-action@master
      with:
        output: codacy-issues.sarif
        format: sarif
        directory: ${GITHUB_WORKSPACE}/web_scraper_all.py
        # Adjust severity of non-security issues
        gh-code-scanning-compat: true
        # Force 0 exit code to allow SARIF file generation
        # This will handover control about PR rejection to the GitHub side
        max-allowed-issues: 2147483647
    
    # Upload the SARIF file generated in the previous step
    - name: Upload SARIF codacy-issues file
      uses: github/codeql-action/upload-sarif@main
      with:
        sarif_file: codacy-issues.sarif
```
After pulling the docker image, the following error occurs:
```cmd
Status: Downloaded newer image for codacy/codacy-analysis-cli:7.6.1
05/16 19:20:39 ERROR c.c.a.c.a.CodacyPluginsAnalyser:31 - Failed analysis for markdownlint 
java.lang.Throwable: 
Docker exited with code 1
stdout: 
stderr: [Error: ENOENT: no such file or directory, open '.markdownlint.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '.markdownlint.json'
}
           
	at com.codacy.plugins.runners.BinaryDockerRunner.$anonfun$run$4(BinaryDockerRunner.scala:84)
	at scala.util.Success.flatMap(Try.scala:251)
	at com.codacy.plugins.runners.BinaryDockerRunner.run(BinaryDockerRunner.scala:69)
	at com.codacy.plugins.results.traits.ToolRunner.$anonfun$apply$2(ToolRunner.scala:77)
	at com.codacy.plugins.results.traits.CodacyDocker$.$anonfun$usingDockerConfig$2(CodacyDocker.scala:45)
	at com.codacy.plugins.utils.FileHelper$.$anonfun$usingNewFile$2(FileHelper.scala:51)
	at scala.util.Try$.apply(Try.scala:213)
	at com.codacy.plugins.utils.FileHelper$.usingNewFile(FileHelper.scala:45)
	at com.codacy.plugins.results.traits.CodacyDocker$.usingConfigPath(CodacyDocker.scala:57)
	at com.codacy.plugins.results.traits.CodacyDocker$.$anonfun$usingDockerConfig$1(CodacyDocker.scala:39)
	at scala.Option.map(Option.scala:230)
	at com.codacy.plugins.results.traits.CodacyDocker$.usingDockerConfig(CodacyDocker.scala:38)
	at com.codacy.plugins.results.traits.ToolRunner.$anonfun$apply$1(ToolRunner.scala:76)
	at scala.util.Try$.apply(Try.scala:213)
	at com.codacy.plugins.results.traits.ToolRunner.apply(ToolRunner.scala:61)
	at com.codacy.plugins.results.traits.ToolRunner.run(ToolRunner.scala:49)
	at com.codacy.analysis.core.tools.Tool.run(Tool.scala:91)
	at com.codacy.analysis.core.analysis.CodacyPluginsAnalyser.analyse(CodacyPluginsAnalyser.scala:25)
	at com.codacy.analysis.cli.analysis.AnalyseExecutor.$anonfun$issues$1(AnalyseExecutor.scala:150)
	at scala.util.Success.flatMap(Try.scala:251)
	at com.codacy.analysis.cli.analysis.AnalyseExecutor.issues(AnalyseExecutor.scala:142)
	at com.codacy.analysis.cli.analysis.AnalyseExecutor.$anonfun$run$5(AnalyseExecutor.scala:66)
	at scala.collection.parallel.AugmentedIterableIterator.map2combiner(RemainsIterator.scala:116)
	at scala.collection.parallel.AugmentedIterableIterator.map2combiner$(RemainsIterator.scala:113)
	at scala.collection.parallel.immutable.ParHashSet$ParHashSetIterator.map2combiner(ParHashSet.scala:81)
	at scala.collection.parallel.ParIterableLike$Map.leaf(ParIterableLike.scala:1056)
	at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:53)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:67)
	at scala.collection.parallel.Task.tryLeaf(Tasks.scala:56)
	at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:50)
	at scala.collection.parallel.ParIterableLike$Map.tryLeaf(ParIterableLike.scala:1053)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal(Tasks.scala:160)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal$(Tasks.scala:157)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.internal(Tasks.scala:440)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute(Tasks.scala:150)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute$(Tasks.scala:149)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:440)
	at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```
How can I fix this?

**Comment by stefanvacareanu7** [comment]
Hi there,

Thanks for reaching out!

I am passing your issue to the Engineering team and keep you posted on any updates.

Kind Regards,
Stefan

**Comment by lolgab** [comment]
Hello @mrtnbm,
Do you have a reproduction of the problem (maybe a public repository we can try)?
We found a problem with our markdownlint tool not handling correctly projects without a `.markdownlint.json` file which we solved in https://github.com/codacy/codacy-markdownlint/pull/8.
Can you check if this solved your problems?

**Comment by mrtnbm** [comment]
Hello @lolgab,

thanks for the PR - this fixed my issue.
