### ISSUE TITLE
[CY-6599] It stuck indefinitely

### ISSUE THREAD

**Issue by ale5000-git** [codacy/codacy-analysis-cli-action#90]
I have interrupted it after 5 hours but it should have taken less than 5 minutes, see here: https://github.com/micro5k/microg-unofficial-installer/actions/runs/3370264747/jobs/5590949415

```
11/01 14:39:14 DEBUG c.c.a.c.s.FileDataStorage:82 - Retrieving storage 
Exception in thread "main" java.util.concurrent.TimeoutException: Futures timed out after [1 minute]
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:259)
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:263)
	at scala.concurrent.Await$.$anonfun$result$1(package.scala:223)
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:57)
	at scala.concurrent.Await$.result(package.scala:146)
	at com.codacy.toolRepository.remote.ToolRepositoryRemote.patternsFromApi(ToolRepositoryRemote.scala:140)
	at com.codacy.toolRepository.remote.ToolRepositoryRemote.downloadPatternsFromApi(ToolRepositoryRemote.scala:145)
	at com.codacy.toolRepository.remote.ToolRepositoryRemote.listPatterns(ToolRepositoryRemote.scala:165)
	at com.codacy.analysis.core.tools.ToolCollector.toTool(Tool.scala:196)
	at com.codacy.analysis.core.tools.ToolCollector.$anonfun$fromLanguages$2(Tool.scala:208)
	at cats.instances.ListInstances$$anon$1.$anonfun$traverse$2(list.scala:78)
	at cats.instances.ListInstances$$anon$1.loop$2(list.scala:68)
	at cats.instances.ListInstances$$anon$1.$anonfun$foldRight$1(list.scala:68)
	at cats.Eval$$anon$6.$anonfun$start$3(Eval.scala:275)
	at cats.Eval$.loop$1(Eval.scala:336)
	at cats.Eval$.cats$Eval$$evaluate(Eval.scala:368)
	at cats.Eval$Defer.value(Eval.scala:257)
	at cats.instances.ListInstances$$anon$1.traverse(list.scala:77)
	at cats.instances.ListInstances$$anon$1.traverse(list.scala:16)
	at cats.Traverse.flatTraverse(Traverse.scala:51)
	at cats.Traverse.flatTraverse$(Traverse.scala:19)
	at cats.instances.ListInstances$$anon$1.flatTraverse(list.scala:16)
	at cats.Traverse$Ops.flatTraverse(Traverse.scala:19)
	at cats.Traverse$Ops.flatTraverse$(Traverse.scala:19)
	at cats.Traverse$ToTraverseOps$$anon$2.flatTraverse(Traverse.scala:19)
	at com.codacy.analysis.core.tools.ToolCollector.$anonfun$fromLanguages$1(Tool.scala:208)
	at scala.util.Either.flatMap(Either.scala:341)
	at com.codacy.analysis.core.tools.ToolCollector.fromLanguages(Tool.scala:207)
	at com.codacy.analysis.cli.analysis.ToolSelector.fromLocalConfig$1(ToolSelector.scala:59)
	at com.codacy.analysis.cli.analysis.ToolSelector.$anonfun$tools$6(ToolSelector.scala:64)
	at scala.util.Either$LeftProjection.flatMap(Either.scala:561)
	at com.codacy.analysis.cli.analysis.ToolSelector.tools(ToolSelector.scala:63)
	at com.codacy.analysis.cli.analysis.ToolSelector.allTools(ToolSelector.scala:27)
	at com.codacy.analysis.cli.analysis.AnalyseExecutor.$anonfun$run$2(AnalyseExecutor.scala:46)
	at scala.util.Either.flatMap(Either.scala:341)
	at com.codacy.analysis.cli.analysis.AnalyseExecutor.run(AnalyseExecutor.scala:41)
	at com.codacy.analysis.cli.command.AnalyseCommand.$anonfun$run$1(AnalyseCommand.scala:110)
	at scala.util.Either.flatMap(Either.scala:341)
	at com.codacy.analysis.cli.command.AnalyseCommand.run(AnalyseCommand.scala:109)
	at com.codacy.analysis.cli.MainImpl.runCommand(Main.scala:19)
	at com.codacy.analysis.cli.MainImpl.run(Main.scala:14)
	at com.codacy.analysis.cli.command.CLIApp.run(CLIApp.scala:21)
	at com.codacy.analysis.cli.command.CLIApp.run(CLIApp.scala:17)
	at com.codacy.analysis.cli.command.CommandAppWithBaseCommand.$anonfun$main$1(CommandAppWithBaseCommand.scala:103)
	at com.codacy.analysis.cli.command.CommandAppWithBaseCommand.$anonfun$main$1$adapted(CommandAppWithBaseCommand.scala:88)
	at scala.Option.foreach(Option.scala:407)
	at com.codacy.analysis.cli.command.CommandAppWithBaseCommand.main(CommandAppWithBaseCommand.scala:88)
	at com.codacy.analysis.cli.Main.main(Main.scala)
```

**Comment by stefanvacareanu7** [comment]
I'm closing this conversation because of a lack of activity. If this is still happening, feel free to open a new issue with the following template

Description:
[Provide a clear and concise description of the issue you are facing. Include any error messages, if applicable.]

Steps to Reproduce:
[If applicable, provide step-by-step instructions on how to reproduce the issue. This helps others understand and fix the problem.]

Expected Behavior:
[Describe what you expected to happen when you performed the above steps.]

Actual Behavior:
[Describe what happened.]

Screenshots:
[If applicable, attach screenshots or images that help illustrate the issue.]

You can open the issue here or contact us at support@codacy.com.
